pip install yacs
pip install numpy==1.17
pip install opencv-python==4.0.1.24
pip install torchvision==0.2.1
pip install thop
pip install pillow==6.1.0
pip install torch
pip install timm==0.1.20
pip install tensorboardx==1.2
pip install adamp
pip install tensorboard
pip install adamp
pip install easydict
