aa: rand-m9-mstd0.5
accumulation_steps: 1
amp: false
data: ../data/imagenet
arch_list:
- 16
- 2
- 0
- 5
- 5
- 1
- 3
- 5
- 1
- 3
- 4
- 1
- 2
- 5
- 4
- 1
- 3
- 3
- 1
- 3
- 1
- 5
- 1
- 0
- 5
- 4
- 4
- 3
- 0
batch_size: 128
color_jitter: 0.4
crop_pct: null
cooldown_epochs: 0
decay_epochs: 2.4
decay_rate: 0.973
dilation: none
dist_bn: ''
drop: 0.2
drop_block: 0.0
drop_path: 0.0
epochs: 350
eval_metric: prec1
gp: avg
gpus: 8
head_alpha: 1
img_size: 224
initial_checkpoint: ../CKP/574.pth.tar
j: 8
log_interval: 50
loss_scale: false
lr: 0.064
lr_noise:
- 0.42
- 0.9
lr_noise_pct: 0.67
lr_noise_std: 1.0
maxup: false
mean: null
min_lr: 1.0e-05
model: ours
model_ema: true
model_ema_decay: 0.9999
model_ema_force_cpu: false
model_selection: 0
momentum: 0.9
multi_scale: false
net_config: ''
no_distributed: false
no_prefetcher: false
no_resume_opt: false
nodes: 2
num_classes: 1000
num_gpu: 1
num_head: 2
opt: rmsproptf
opt_eps: 0.001
output: ''
patience_epochs: 10
pin_mem: false
pool_bn: false
pretrained: false
recount: 1
recovery_interval: 0
remode: pixel
reprob: 0.2
resplit: false
resume: ''
sched: cosine
seed: 42
smoothing: 0.1
start_epoch: null
std: null
sync_bn: false
temp: 2
train_interpolation: random
tta: 0
validation_batch_size_multiplier: 4
warmup_epochs: 3
warmup_lr: 1.0e-06
weight_decay: 1.0e-05
width_mul: 1.0
workers: 4
zero_gamma: false
